export const GET_MOVIE_API = 'GET_MOVIE_API';

export const GET_THEATER_API = 'GET_THEATER_API';

export const GET_THEATER_INFO_API = 'GET_THEATER_INFO_API';

export const GET_THEATER_SHOWTIME_API = 'GET_THEATER_SHOWTIME_API';

export const GET_MOVIE_INFO_API = 'GET_MOVIE_INFO_API';

export const GET_MOVIE_SHOWTIME_API = 'GET_MOVIE_SHOWTIME_API';
